[
    {
        "Classification": "jupyter-s3-conf",
        "Properties": {
            "s3.persistence.enabled": "true",
            "s3.persistence.bucket": "emr-jupyter-notebooks-zjasdu123"
        }
    }
]