project:
  type: book

lang: pl
language: _language.yml

book: 
  title: "Wieloskalowa analiza danych z forum internetowego przy użyciu usług chmury AWS"
  author: "Michał Kamiński"
  chapters:
    - index.qmd
    - part: intro.qmd
    - part: results.qmd
      chapters:
      - 00_schema.qmd
      - 01_preprocessing.qmd
      - 02_analytics.qmd
    - references.qmd
    - attachments.qmd

bibliography: references.bib
format:
  html:
    theme: cosmo
  pdf:
    cite-method: biblatex
    documentclass: scrreprt
    margin-bottom: 2cm
    margin-right: 2cm
    margin-top: 2cm
    margin-left: 2.5cm
    header-includes: |
      \usepackage{titling}
      \setlength{\droptitle}{-3cm}
      \pretitle{
        \begin{center}
        \includegraphics[width=16cm,height=2.54cm]{images/pw_logo.jpg}\\ % cover figure
        \vspace{1cm}
        \normalsize
        Instytut Informatyki \\
        \vspace{1.5cm}
        \Large
        Studia Podyplomowe \\
        Big Data - przetwarzanie i analiza dużych zbiorów danych \\
        \vspace{2cm}
        PRACA KOŃCOWA \\
        \vspace{1cm}
      }
      \posttitle{
        \vspace{3cm}
        \author{Michał Kamiński}
        \end{center}
        }
      \preauthor{\begin{center}}
      \postauthor{
        Warszawa, 2023
        \end{center}
      }