project:
  type: book

lang: pl
language: _language.yml

book: 
  title: "Wieloskalowa analiza danych z forum internetowego przy użyciu usług chmury AWS"
  author: "Michał Kamiński"
  date: today
  chapters:
    - index.qmd
    - part: intro.qmd
    - part: results.qmd
      chapters:
      - 00_schema.qmd
      - 01_preprocessing.qmd
      - 02_analytics.qmd
    - references.qmd
    - attachments.qmd

bibliography: references.bib
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    margin-bottom: 2cm
    margin-right: 2cm
    margin-top: 2cm
    margin-left: 2.5cm

